In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
#Creating sample array
arr = np.arange(0,11)

In [4]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#Get a value at an index
arr[8]

8

In [6]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [7]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
# Reset array, we'll see why i had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [11]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [12]:
# Now note the changes also occur in our original array!
arr

# Data is not copied, it's a view of the original array! This avoids memory problems!

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [13]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
# Indexing a 2D array

arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [15]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [16]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [17]:
# Getting individual element value
arr_2d[1,0]

20

In [18]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [19]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [20]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [24]:
#Fancy Indexing

#Set up matrix
arr_2d = np.zeros((10,10)

SyntaxError: unexpected EOF while parsing (<ipython-input-24-9460c35b8347>, line 4)

In [22]:
#Length of array
arr_length = arr2d.shape[1]

NameError: name 'arr2d' is not defined

In [25]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

NameError: name 'arr_length' is not defined

In [26]:


#Fancy indexing allows the following
arr2d[[2,4,6,8]]



NameError: name 'arr2d' is not defined